export { default as HomeHero } from './hero'
export { default as HomePopularCourse } from './popular-courses'
export { default as HomeBenefit } from './benefit'
export { default as HomeTestimonial } from './testimonial'
export { default as HomeOurFeatures } from './features'
export { default as HomeNewsLetter } from './newsletter'
